### PR TITLE
Install decidim awesome

### PR DESCRIPTION
**Pull request by fblupi**

### CODE REVIEW

**Review by verarojman — CHANGES_REQUESTED** [review]
Hi there @fblupi! Thanks for your contribution :)

You need to add the `node_modules/` directory to `.gitignore` and remove it with `git rm -r node_modules/` (we shouldn't add automatically generated files to the repository).

Could you do this so I can see only the changes related to the decidim-awesome gem, and review your PR in depth? Thanks in advance 🙌🏾

**Comment by fblupi** [comment]
> Hi there @fblupi! Thanks for your contribution :)
> 
> You need to add the `node_modules/` directory to `.gitignore` and remove it with `git rm -r node_modules/` (we shouldn't add automatically generated files to the repository).
> 
> Could you do this so I can see only the changes related to the decidim-awesome gem, and review your PR in depth? Thanks in advance 🙌🏾

Done!

**Review by verarojman — CHANGES_REQUESTED** [review]
Your PR's looking awesome now! 😎  (see what I did there? hehehehe)

Maybe you could add some tests to ensure some basic decidim-awesome features are working as expected, check these system specs ➡️  https://github.com/Platoniq/decidim-getxo/blob/main/spec/system/awesome_tests_spec.rb

Thank you! ♥️

**Review by verarojman — APPROVED** [review]
Actually, let's already merge this so you can deploy the first version, and you can submit a PR adding some specs later ;)

**Pull request merged**
